[package]
name = "codealong"
version = "0.1.0"
authors = ["ghempton"]

[dependencies]
git2 = "0.7"
glob = "0.2"
chrono = "0.4"
regex = "1"
lazy_static = "1.1.0"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8"
