[package]
name = "codealong-github"
version = "0.1.0"
authors = ["Gordon Hempton <ghempton@gmail.com>"]

[dependencies]
codealong = { path = "../codealong" }
regex = "1"
lazy_static = "1.1.0"
reqwest = "0.9.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

