[package]
name = "codealong-cli"
version = "0.1.0"
authors = ["Gordon Hempton <ghempton@gmail.com>"]

[dependencies]
codealong = { path = "../codealong" }
codealong-elk = { path = "../codealong-elk" }
clap = {git = "https://github.com/clap-rs/clap", branch = "v3-dev",  features = ["yaml"]}
git2 = "0.7"
indicatif = "0.9"
